/* eslint-disable */
import { FuseNavigationItem } from '@fuse/components/navigation';
export const defaultNavigation: FuseNavigationItem[] = [
    {
        id: 'sites',
        title: 'Sites',
        type: 'basic',
        icon: 'heroicons_outline:globe-europe-africa',
        link: '/sites',
    },
    {
        id: 'products',
        title: 'Products',
        type: 'basic',
        icon: 'heroicons_outline:lifebuoy',
        link: '/products',
    },
    {
        id: 'projects',
        title: 'Projects',
        type: 'basic',
        icon: 'heroicons_outline:newspaper',
        link: '/projects',
    },

    {
        id: 'leases',
        title: 'Leases',
        type: 'basic',
        icon: 'heroicons_outline:document-text',
        link: '/lease-agreements',
    },
    {
        id: 'payments',
        title: 'payments',
        type: 'basic',
        icon: 'heroicons_outline:banknotes',
        link: '/payments',
    },
    {
        id: 'templates',
        title: 'Templates',
        type: 'basic',
        icon: 'heroicons_outline:squares-2x2',
        link: '/templates',
    },
    {
        id: 'documentation',
        title: 'File Manager',
        type: 'basic',
        icon: 'heroicons_outline:document-magnifying-glass',
        link: '/documentation',
    },
    {
        id: 'iam',
        title: 'Iam',
        type: 'basic',
        icon: 'heroicons_outline:finger-print',
        link: '/iam',
    },
];
export const compactNavigation: FuseNavigationItem[] = [
    {
        id: 'sites',
        title: 'Sites',
        type: 'basic',
        icon: 'heroicons_outline:globe-europe-africa',
        link: '/sites',
    },
    {
        id: 'products',
        title: 'Products',
        type: 'basic',
        icon: 'heroicons_outline:lifebuoy',
        link: '/products',
    },
    {
        id: 'projects',
        title: 'Projects',
        type: 'basic',
        icon: 'heroicons_outline:newspaper',
        link: '/projects',
    },

    {
        id: 'leases',
        title: 'Leases',
        type: 'basic',
        icon: 'heroicons_outline:document-text',
        link: '/lease-agreements',
    },
    {
        id: 'payments',
        title: 'payments',
        type: 'basic',
        icon: 'heroicons_outline:banknotes',
        link: '/payments',
    },
    {
        id: 'templates',
        title: 'Templates',
        type: 'basic',
        icon: 'heroicons_outline:squares-2x2',
        link: '/templates',
    },
    {
        id: 'documentation',
        title: 'File Manager',
        type: 'basic',
        icon: 'heroicons_outline:document-magnifying-glass',
        link: '/documentation',
    },
    {
        id: 'iam',
        title: 'Iam',
        type: 'basic',
        icon: 'heroicons_outline:finger-print',
        link: '/iam',
    },
];
export const futuristicNavigation: FuseNavigationItem[] = [
    {
        id: 'sites',
        title: 'Sites',
        type: 'basic',
        icon: 'heroicons_outline:globe-europe-africa',
        link: '/sites',
    },
    {
        id: 'products',
        title: 'Products',
        type: 'basic',
        icon: 'heroicons_outline:lifebuoy',
        link: '/products',
    },
    {
        id: 'projects',
        title: 'Projects',
        type: 'basic',
        icon: 'heroicons_outline:newspaper',
        link: '/projects',
    },

    {
        id: 'leases',
        title: 'Leases',
        type: 'basic',
        icon: 'heroicons_outline:document-text',
        link: '/lease-agreements',
    },
    {
        id: 'payments',
        title: 'payments',
        type: 'basic',
        icon: 'heroicons_outline:banknotes',
        link: '/payments',
    },
    {
        id: 'templates',
        title: 'Templates',
        type: 'basic',
        icon: 'heroicons_outline:squares-2x2',
        link: '/templates',
    },
    {
        id: 'documentation',
        title: 'File Manager',
        type: 'basic',
        icon: 'heroicons_outline:document-magnifying-glass',
        link: '/documentation',
    },
    {
        id: 'iam',
        title: 'Iam',
        type: 'basic',
        icon: 'heroicons_outline:finger-print',
        link: '/iam',
    },
];
export const horizontalNavigation: FuseNavigationItem[] = [
    {
        id: 'sites',
        title: 'Sites',
        type: 'basic',
        icon: 'heroicons_outline:globe-europe-africa',
        link: '/sites',
    },
    {
        id: 'products',
        title: 'Products',
        type: 'basic',
        icon: 'heroicons_outline:lifebuoy',
        link: '/products',
    },
    {
        id: 'projects',
        title: 'Projects',
        type: 'basic',
        icon: 'heroicons_outline:newspaper',
        link: '/projects',
    },
    {
        id: 'leases',
        title: 'Leases',
        type: 'basic',
        icon: 'heroicons_outline:document-text',
        link: '/lease-agreements',
    },
    {
        id: 'payments',
        title: 'payments',
        type: 'basic',
        icon: 'heroicons_outline:banknotes',
        link: '/payments',
    },
    {
        id: 'templates',
        title: 'Templates',
        type: 'basic',
        icon: 'heroicons_outline:squares-2x2',
        link: '/templates',
    },
    {
        id: 'documentation',
        title: 'File Manager',
        type: 'basic',
        icon: 'heroicons_outline:document-magnifying-glass',
        link: '/documentation',
    },
    {
        id: 'iam',
        title: 'Iam',
        type: 'basic',
        icon: 'heroicons_outline:finger-print',
        link: '/iam',
    },
];
